require("harrison.init")
require("after.which-key")
require("after.colors")
require("after.tree-sitter")
require("after.prettier")
require("after.lsp")
require("after.git")
require("after.telescope")
require("after.harpoon")
require("after.lualine")

require("gitsigns").setup({})
